# Generated by Django 3.1.7 on 2021-03-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0002_auto_20210328_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
