# Generated by Django 3.1.7 on 2021-03-31 09:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_store', '0004_useraccount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAccount',
            new_name='Profile',
        ),
    ]
