# Generated by Django 3.1.7 on 2021-03-31 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0005_auto_20210331_1206'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
