# Generated by Django 3.1.7 on 2021-04-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0007_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='-', max_length=250),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
