# Generated by Django 3.1.7 on 2021-04-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0008_auto_20210401_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=250),
        ),
    ]
