# Generated by Django 3.1.7 on 2021-04-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0009_auto_20210401_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
