# Generated by Django 3.1.7 on 2021-04-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0011_auto_20210401_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferred_communication',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
