# Generated by Django 3.1.7 on 2021-04-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0014_auto_20210401_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('USER', 'User')], max_length=5, null=True),
        ),
    ]
