# Generated by Django 3.1.7 on 2021-04-01 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0025_auto_20210401_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='preferred_communication',
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=250, null=True),
        ),
    ]
