# Generated by Django 3.1.7 on 2021-04-02 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0026_auto_20210401_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
    ]
