# Generated by Django 3.1.7 on 2021-04-05 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0029_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
