# Generated by Django 2.1.5 on 2021-04-07 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0030_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='in_stock',
        ),
    ]
