# Generated by Django 2.1.5 on 2021-04-09 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0035_auto_20210408_2231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='profile_picture',
        ),
    ]
