# Generated by Django 2.1.5 on 2021-04-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0036_auto_20210409_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='payment_options',
            field=models.CharField(choices=[('S', 'Stripe'), ('P', 'Paypal')], default='S', max_length=50),
        ),
    ]
