# Generated by Django 2.1.5 on 2021-04-09 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0037_billingaddress_payment_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingaddress',
            name='payment_options',
        ),
    ]
