# Generated by Django 2.1.5 on 2021-04-13 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0044_address_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='order_id',
            new_name='order',
        ),
    ]
