# Generated by Django 2.1.5 on 2021-04-13 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0045_auto_20210413_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='order',
        ),
    ]
