# Generated by Django 2.1.5 on 2021-04-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0046_remove_address_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='order_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
