# Generated by Django 2.1.5 on 2021-04-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0048_remove_address_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='-', max_length=250),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(default='-', max_length=300),
        ),
    ]
