# Generated by Django 2.1.5 on 2021-04-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0050_auto_20210414_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='in_stock',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
