# Generated by Django 2.1.5 on 2021-04-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0052_auto_20210414_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
